name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile app.yaml
        run: cat app.template.yaml | envsubst > app.yaml
        env:
          DSN: ${{ secrets.gcp_sql_dsn }}
      - name: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
